namespace Intercom.Discovery;

using Intercom.Identity;

/// <summary>
/// What this device advertises on `_intercom._tcp.local` per eligible
/// interface. SRV carries Port (host is implicit — the interface's own
/// address); TXT carries ProtocolVersion, PeerIdHint, and the public SPKI
/// fingerprint needed to route and verify the subsequent TLS connection:
/// no friendly name tied to a person, no capability set, no presence/DND
/// state. The friendly instance name DNS-SD itself requires is presentation
/// data, not identity, and is generated by the registration layer, not
/// carried here.
/// </summary>
public sealed record ServiceAdvertisement
{
    public required int ProtocolVersion { get; init; }
    public required PeerIdHint PeerIdHint { get; init; }
    public SpkiPin? Spki { get; init; }

    /// <summary>TCP port the control channel (issue #21) will listen on.
    /// Discovery only advertises it; it does not open or manage that
    /// listener.</summary>
    public required int Port { get; init; }
}
